language: python
cache: pip

services:
  - postgresql

python:
  - "3.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE=nrc.conf.ci
    - PGUSER=postgres
    - DB_USER=postgres
    - PGDATABASE=postgres
    - PGPASSWORD=
    - DB_PASSWORD=

  matrix:
    - TOXENV=django_tests
    - TOXENV=black

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV

notifications:
  email: false
