language: python
cache: pip

services:
  - postgresql

python:
  - "3.6"

env:
  global:
    - PGUSER=postgres
    - PGDATABASE=postgres
    - PGPASSWORD=
  matrix:
    - DJANGO=2.2

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: TOXENV=django_tests }
    - { python: "3.6", env: TOXENV=black }

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
