# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres:11-alpine
    # environment:
    #   - POSTGRES_USER=${PG_USER:notifications}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:notifications}

  rabbitmq:
    image: rabbitmq:3.7-alpine
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest

  web:
    build:
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=notifications.conf.docker
      - SECRET_KEY=${SECRET_KEY}
      - PUBLISH_BROKER_URL=amqp://guest:guest@rabbitmq:5672/%2F
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
