# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres:11-alpine
    # environment:
    #   - POSTGRES_USER=${PG_USER:nrc}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:nrc}

  rabbitmq:
    image: rabbitmq:3.7-alpine
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest

  celery:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=nrc.conf.envs.docker
      - SECRET_KEY=${SECRET_KEY:-\(,gc7VE(#CO<zCR3e(lRtOsw5q+U2DpG5o\X#P4PVRm*=u|E%}
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      # - CACHE_DEFAULT=redis:6379/0
      # - CACHE_AXES=redis:6379/0
      - RABBITMQ_HOST=rabbitmq
      - PUBLISH_BROKER_URL=amqp://guest:guest@rabbitmq:5672/%2F
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
      - CELERY_LOGLEVEL=DEBUG
    command: /celery_worker.sh
    depends_on:
      - db
      - rabbitmq

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=nrc.conf.docker
      - SECRET_KEY=${SECRET_KEY}
      - RABBITMQ_HOST=rabbitmq
      - PUBLISH_BROKER_URL=amqp://guest:guest@rabbitmq:5672/%2F
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
