# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres:11-alpine
    # environment:
    #   - POSTGRES_USER=${PG_USER:notifications}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:notifications}
  web:
    image: vngr/gemma-notifications
    environment:
      - DJANGO_SETTINGS_MODULE=notifications.conf.docker
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db
