apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.settings.name }}-rabbitmq
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}-rabbitmq
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.settings.name }}-rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
