apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  secret-key: {{ .Values.settings.secret | b64enc | quote }}

  db-host: {{ .Values.postgres.url | b64enc | quote }}
  db-port: {{ .Values.postgres.port | toString | b64enc }}
  db-user: {{ .Values.postgres.user | b64enc | quote }}
  db-password: {{ .Values.postgres.password | b64enc | quote }}
  db-name: {{ .Values.postgres.database | b64enc | quote }}

  publish-broker-url: {{ .Values.celery.publish.brokerUrl | b64enc }}

  rabbitmq-default-user: {{ .Values.rabbitMq.defaultUser | b64enc }}
  rabbitmq-default-password: {{ .Values.rabbitMq.defaultPassword | b64enc }}

  celery-broker-url: {{ .Values.celery.brokerUrl | b64enc }}
  celery-result-backend: {{ .Values.celery.resultBackend | b64enc }}

  {{ if .Values.settings.dsn }}  sentry-dsn: {{ .Values.settings.dsn | b64enc | quote }}{{ end }}
