---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rabbitmq-nrc
  namespace: gemma
  labels:
    k8s-app: rabbitmq-nrc
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: rabbitmq-nrc
  template:
    metadata:
      name: rabbitmq-nrc
      labels:
        k8s-app: rabbitmq-nrc
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-alpine
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: <REDACTED>
          - name: RABBITMQ_DEFAULT_PASS
            value: <REDACTED>

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-nrc
  namespace: gemma
  labels:
    k8s-app: rabbitmq-nrc
spec:
  selector:
    k8s-app: rabbitmq-nrc
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
