---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nrc
  namespace: gemma
  labels:
    k8s-app: nrc
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nrc
  template:
    metadata:
      name: nrc
      labels:
        k8s-app: nrc
    spec:
      containers:
      - name: nrc
        image: vngr/gemma-notifications:latest
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: nrc.conf.docker
          - name: SUBPATH
            value: /nrc
          - name: DB_HOST
            value: postgres-nrc
          - name: SECRET_KEY
            value: <REDACTED>
          - name: DB_PASSWORD
            value: <REDACTED>
          - name: PUBLISH_BROKER_URL
            value: amqp://<REDACTED>:<REDACTED>@rabbitmq-nrc:5672/%2F
          - name: CELERY_BROKER_URL
            value: amqp://<REDACTED>:<REDACTED>@rabbitmq-nrc:5672//
          - name: CELERY_RESULT_BACKEND
            value: amqp://<REDACTED>:<REDACTED>@rabbitmq-nrc:5672//
          - name: SENTRY_DSN
            value: <REDACTED>

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: nrc
  namespace: gemma
  labels:
    k8s-app: nrc
spec:
  selector:
    k8s-app: nrc
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
