# Default values for open-zaak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

settings:
  name: opennotificaties
  subdomain: opennotificaties
  domain: zuid-drecht.nl
  env: dev
  module: nrc.conf.docker
  secret: 7y82z1%ef)k@f=u-_%ri71lk4=7jy^z5#@6d4*92=t@p0-yk5k
  dsn:
  version: latest
  pullPolicy: Always
  debug: 1

security:
  allowedHosts: '*'

email:
  url: localhost
  port: 867
  user: email
  password: '!changeMe!'

rabbitMq:
  port: 5672
  defaultUser: opennotificaties
  defaultPassword: '!changeMe!'
  memory: 100Mi
  cpu: 100m
  limits:
    memory: 200Mi
    cpu: 250m

celery:
  publish:
    brokerUrl: amqp://opennotificaties:!changeMe!@opennotificaties-rabbitmq:5672/%2F
  brokerUrl: amqp://opennotificaties:!changeMe!@opennotificaties-rabbitmq:5672//
  resultBackend: amqp://opennotificaties:!changeMe!@opennotificaties-rabbitmq:5672//
  memory: 500Mi
  cpu: 200m
  limits:
    memory: 1Gi
    cpu: 500m

postgres:
  url: localhost
  port: 5432
  user: opennotificaties
  password: '!changeMe!'
  database: opennotificaties

redis:
  port: 6379
  version: 5.0
  database: opennotificaties
  memory: 100Mi
  cpu: 100m
  limits:
    memory: 200Mi
    cpu: 250m

web:
  memory: 500Mi
  cpu: 200m
  limits:
    memory: 1Gi
    cpu: 500m

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
